version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: "/home/oa/logs/oaserver.log"
    when: midnight  # 每天午夜轮换
    interval: 1  # 每 1 天轮换一次
    backupCount: 7  # 只保留最近 7 天的日志
    encoding: utf8
    formatter: default

loggers:
  uvicorn:
    level: INFO
    handlers: [file]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [file]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [file]
    propagate: no
